version: '3.4'

services:
  nest:
    image: nest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      - 5000:5000
  db:
    image: postgres:14.1-alpine
    depends_on:
     - db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=grimm
      - POSTGRES_DB=djobsdb
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
